#!/usr/bin/expect

set variable [lindex $argv 0];
set variable2 [lindex $argv 1];

spawn ssh it_access@192.168.150.196

expect '$ '

send "python3 prueba_ssh.py\r"

expect 'dame una palabra:'

send "$variable\r"

expect 'dame otra palabra:'

send "$variable2\r"

expect "$variable$variable2"

expect '$ '

send "exit\r"

expect EOF
